identifier: config-props-product-service 
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/product"
    username: root
    password: ENC(8ZZUKRAhH6CQ+HWQ6+067iYvSxV47+Mp)
server:
  port: 8282
  servlet:
    context-path: /api
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client: 
      client-id: appl
      client-secret: secret
      user-authorization-uri: http://localhost:9191/oauth/authorize
      access-token-uri: http://localhost:9191/oauth/token
