identifier: config-props-product-service 
spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:orcl"
    username: system
    password: ENC(Hk6H1qjFON6wXk/pGzWb21NtnMHaMbiu)
jasypt:
  encryptor:
    password: AmirDB

server:
  port: 8282
  servlet:
    context-path: /api
