identifier: config-props-product-service 
spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:xe"
    username: system
    password: ENC(1ZF5y+RzZc8m61cKHRt7vg==)

jasypt:
  encryptor:
    password: AmirDB

server:
  port: 8282
  servlet:
    context-path: /api
