identifier: config-props-product-service 
spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:orcl"
    username: system
    password: ENC(Hk6H1qjFON6wXk/pGzWb21NtnMHaMbiu)
    driver-class-name: oracle.jdbc.driver.OracleDriver
spring:
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.Oracle10gDialect

jasypt:
  encryptor:
    password: AmirDB

server:
  port: 8282
  servlet:
    context-path: /api
